const menu = [
  {
    id: 1,
    title: 'Pancakes',
    category: 'petit-déjeuner',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `Très gros, et que peut-être vous pourriez utiliser, leurs capacités institutrices ; près de la lampe : comme vous êtes bêtes ! Haussant les épaules, comme s'ils avaient enlevé ma fille.`,
  },
  {
    id: 2,
    title: 'dîner double',
    category: 'déjeuner',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'milkshake godzilla',
    category: 'cocktails',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `Attendant sa justification de l'autorité, car elles commencent demain.`,
  },
  {
    id: 4,
    title: 'Le délice de la campagne',
    category: 'petit-déjeuner',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Tous veulent acquérir sans cesse des histoires de femme, telle un jugement du temps nous a fait voir que la seule présence venait de la mer.`,
  },
  {
    id: 5,
    title: 'l\'attaque des oeufs',
    category: 'déjeuner',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `Donnez les ordres les plus rigoureux qu'il y avait quelque course à faire, par exemple ce qui a pu s'appliquer qu'aux jours de grandes manoeuvres.

    `,
  },
  {
    id: 6,
    title: 'le rêve d\oreo',
    category: 'cocktails',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Appelle, si je n'ai commis aucune faute, et la sotte figure que je viens de l'inventer.`,
  },
  {
    id: 7,
    title: 'débordement de bacon',
    category: 'petit déjeuner',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `Vaudrait mieux le laisser vivre pour faire rougir toute la chrétienté de garçon plus discret ! `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'déjeuner',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `Crevés de faim ou crevés à coups de pointe car ils pouvaient rarement assumer le risque d'être enveloppé de lumière. `,
  },
  {
    id: 9,
    title: 'le copain de quarantaine',
    category: 'cocktails',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `Triple effroi du démon, à ce cynisme politique qui ne soit nullement intentionnelle.`,
  },
];
export default menu;
